"""
Auto-generated by StateEye.
Run with: python generated_tests.py
"""

from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

BASE_URL = "http://localhost:8000/"
HEADLESS = False
TESTS = [
  {
    "id": 1,
    "actions": [],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_1.png",
    "title": "StateEye Demo"
  },
  {
    "id": 2,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_2.png",
    "title": "StateEye Demo"
  },
  {
    "id": 3,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_3.png",
    "title": "StateEye Demo"
  },
  {
    "id": 4,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel A",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(1)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel A"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_4.png",
    "title": "StateEye Demo"
  },
  {
    "id": 5,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel B",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(2)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel B"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_5.png",
    "title": "StateEye Demo"
  },
  {
    "id": 6,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel C",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(3)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel C"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_6.png",
    "title": "StateEye Demo"
  },
  {
    "id": 7,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel A",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(1)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel A"
      },
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_7.png",
    "title": "StateEye Demo"
  },
  {
    "id": 8,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel A",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(1)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel A"
      },
      {
        "name": "Show Panel A",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(1)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel A"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_8.png",
    "title": "StateEye Demo"
  },
  {
    "id": 9,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel A",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(1)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel A"
      },
      {
        "name": "Show Panel B",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(2)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel B"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_9.png",
    "title": "StateEye Demo"
  },
  {
    "id": 10,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel A",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(1)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel A"
      },
      {
        "name": "Show Panel C",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(3)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel C"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_10.png",
    "title": "StateEye Demo"
  },
  {
    "id": 11,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel B",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(2)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel B"
      },
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_11.png",
    "title": "StateEye Demo"
  },
  {
    "id": 12,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel B",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(2)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel B"
      },
      {
        "name": "Show Panel A",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(1)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel A"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_12.png",
    "title": "StateEye Demo"
  },
  {
    "id": 13,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel B",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(2)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel B"
      },
      {
        "name": "Show Panel B",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(2)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel B"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_13.png",
    "title": "StateEye Demo"
  },
  {
    "id": 14,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel B",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(2)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel B"
      },
      {
        "name": "Show Panel C",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(3)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel C"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_14.png",
    "title": "StateEye Demo"
  },
  {
    "id": 15,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel C",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(3)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel C"
      },
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_15.png",
    "title": "StateEye Demo"
  },
  {
    "id": 16,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel C",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(3)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel C"
      },
      {
        "name": "Show Panel A",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(1)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel A"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_16.png",
    "title": "StateEye Demo"
  },
  {
    "id": 17,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel C",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(3)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel C"
      },
      {
        "name": "Show Panel B",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(2)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel B"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_17.png",
    "title": "StateEye Demo"
  },
  {
    "id": 18,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel C",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(3)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel C"
      },
      {
        "name": "Show Panel C",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(3)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel C"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_18.png",
    "title": "StateEye Demo"
  },
  {
    "id": 19,
    "actions": [
      {
        "name": "Login",
        "selector": "#login-btn",
        "action_type": "click",
        "value": null,
        "description": "Login"
      },
      {
        "name": "Show Panel C",
        "selector": "section:nth-of-type(2) > button.action-btn:nth-of-type(3)",
        "action_type": "click",
        "value": null,
        "description": "Show Panel C"
      },
      {
        "name": "Save",
        "selector": "#save-note",
        "action_type": "click",
        "value": null,
        "description": "Save"
      }
    ],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251218-121506\\artifacts\\state_19.png",
    "title": "StateEye Demo"
  }
]


def replay_actions(page, actions):
    page.goto(BASE_URL, wait_until="domcontentloaded")
    for action in actions:
        el = page.query_selector(action["selector"])
        if not el:
            continue
        if action["action_type"] == "click":
            el.click()
        elif action["action_type"] == "fill":
            el.fill(action.get("value") or "test")
        elif action["action_type"] == "submit":
            el.evaluate("(node) => node.submit && node.submit()")


def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=HEADLESS)
        page = browser.new_page()
        for test in TESTS:
            try:
                replay_actions(page, test["actions"])
                page.screenshot(path=test["artifact"], full_page=True)
                print(f"Captured state {test['id']} -> {test['artifact']}")
            except PlaywrightTimeoutError:
                print(f"Timeout while executing test {test['id']}")
        browser.close()


if __name__ == "__main__":
    main()
