"""
Generate lightweight Playwright regression tests from crawled states.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import List

from .analyzer import AnalysisSummary
from .storage import StateEyeDB


def _load_actions(state_row) -> List[dict]:
    raw = state_row["path_json"] or "[]"
    return json.loads(raw)


def generate_tests(db: StateEyeDB, run_id: int, summary: AnalysisSummary, dst: Path) -> Path:
    run = db.fetch_run(run_id)
    base_url = run["url"]
    cfg = json.loads(run["config_json"])
    headless = cfg.get("headless", True)

    states = {row["id"]: row for row in db.fetch_states(run_id)}
    targets = summary.unique_states or list(states.keys())

    dst = Path(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    artifacts_dir = dst.parent / "artifacts"
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    tests_payload = []
    for sid in targets:
        state = states[sid]
        tests_payload.append(
            {
                "id": sid,
                "actions": _load_actions(state),
                "expected_url": state["url"],
                "artifact": str(artifacts_dir / f"state_{sid}.png"),
                "title": state["title"],
            }
        )

    template = f'''"""
Auto-generated by StateEye.
Run with: python {dst.name}
"""

from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

BASE_URL = "{base_url}"
HEADLESS = {str(headless)}
TESTS = {json.dumps(tests_payload, indent=2)}


def replay_actions(page, actions):
    page.goto(BASE_URL, wait_until="domcontentloaded")
    for action in actions:
        el = page.query_selector(action["selector"])
        if not el:
            continue
        if action["action_type"] == "click":
            el.click()
        elif action["action_type"] == "fill":
            el.fill(action.get("value") or "test")
        elif action["action_type"] == "submit":
            el.evaluate("(node) => node.submit && node.submit()")


def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=HEADLESS)
        page = browser.new_page()
        for test in TESTS:
            try:
                replay_actions(page, test["actions"])
                page.screenshot(path=test["artifact"], full_page=True)
                print(f"Captured state {{test['id']}} -> {{test['artifact']}}")
            except PlaywrightTimeoutError:
                print(f"Timeout while executing test {{test['id']}}")
        browser.close()


if __name__ == "__main__":
    main()
'''
    dst.write_text(template, encoding="utf-8")
    return dst

