"""
Auto-generated by StateEye.
Run with: python generated_tests.py
"""

from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError

BASE_URL = "http://localhost:8000/"
HEADLESS = False
TESTS = [
  {
    "id": 1,
    "actions": [],
    "expected_url": "http://localhost:8000/",
    "artifact": "stateeye_runs\\localhost_8000-output-20251216-215011\\artifacts\\state_1.png",
    "title": "StateEye Demo"
  }
]


def replay_actions(page, actions):
    page.goto(BASE_URL, wait_until="domcontentloaded")
    for action in actions:
        el = page.query_selector(action["selector"])
        if not el:
            continue
        if action["action_type"] == "click":
            el.click()
        elif action["action_type"] == "fill":
            el.fill(action.get("value") or "test")
        elif action["action_type"] == "submit":
            el.evaluate("(node) => node.submit && node.submit()")


def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=HEADLESS)
        page = browser.new_page()
        for test in TESTS:
            try:
                replay_actions(page, test["actions"])
                page.screenshot(path=test["artifact"], full_page=True)
                print(f"Captured state {test['id']} -> {test['artifact']}")
            except PlaywrightTimeoutError:
                print(f"Timeout while executing test {test['id']}")
        browser.close()


if __name__ == "__main__":
    main()
